Update .chezmoiignore Update .chezmoiscripts/30_pull_after_fcitx5_rime_sync_tar_updated Update .chezmoiscripts/90_push_after_fcitx5_rime_sync Update fcitx5-rime-sync.tar.asc Add secrets_chezmoi_blob.json.asc

diff --git a/.chezmoiscripts/run_onchange_30_pull_after_fcitx5_rime_sync_tar_updated.tmpl b/.chezmoiscripts/run_onchange_30_pull_after_fcitx5_rime_sync_tar_updated.tmpl
--- a/.chezmoiscripts/run_onchange_30_pull_after_fcitx5_rime_sync_tar_updated.tmpl
+++ b/.chezmoiscripts/run_onchange_30_pull_after_fcitx5_rime_sync_tar_updated.tmpl
@@ -9,21 +9,28 @@ set -eu
 
 # run on this change: {{ output "sh" "-c" (printf "if [ -f %q ]; then git hash-object %q; else printf missing; fi" $encrypted_tar_file $encrypted_tar_file)}}
 
-if ! git lfs version >/dev/null 2>&1; then
-  echo "pull-fcitx5-rime-sync: git-lfs not available, skip" >&2
-  exit 0
-fi
-
 TARGET_PATH={{ printf "%q" $target_path }}
 ENCRYPTED_TAR_FILE={{ printf "%q" $encrypted_tar_file }}
 
-if [ ! -f "$ENCRYPTED_TAR_FILE" ]; then
-  echo "pull-fcitx5-rime-sync: fcitx5-rime-sync.tar.asc is in Git LFS, but git-lfs not available, skip" >&2
-  exit 0
-fi
-
 TMP_TAR_FILE="$(mktemp)"
 trap 'rm -f "$TMP_TAR_FILE"' EXIT HUP INT TERM
+
+# Pull from chezmoi-blob
+S3_BASE_URL=https://chezmoi-blob.loliis.top
+S3_BUCKET=chezmoi-blob
+REMOTE_KEY=files/fcitx5-rime-sync.tar.asc
+response_status=$(curl -sL \
+  -w "%{http_code}" \
+  "$S3_BASE_URL/$S3_BUCKET/$REMOTE_KEY" \
+  -o "$ENCRYPTED_TAR_FILE")
+if [ "$response_status" = "404" ]; then
+    echo "pull-fcitx5-rime-sync: chezmoi-blob not found, skip"
+    # 如果 404 了，可以选择直接退出脚本，或者跳过解密环节
+    exit 0 
+elif [ "$response_status" != "200" ]; then
+    echo "pull-fcitx5-rime-sync: chezmoi-blob download failed with status $response_status"
+    exit 1
+fi
 
 chezmoi decrypt --output "$TMP_TAR_FILE" "$ENCRYPTED_TAR_FILE"
 {{- if not $in_termux }}
@@ -32,4 +39,5 @@ tar -x -f "$TMP_TAR_FILE" -C "$TARGET_PATH"
 sudo tar -x -f "$TMP_TAR_FILE" -C "$TARGET_PATH"
 sudo chown -R u0_a884:ext_data_rw "$TARGET_PATH"
 {{- end }}
+
 echo "pull-fcitx5-rime-sync: finished!"
